### ISSUE TITLE
Getting Error "cannot import getoutput as shell"

### ISSUE THREAD

**Issue by FireHead90544** [Bitwise-01/YouTubeViews-#36]
When i am trying to run the script i am getting the error cannot import getoutput as shell

**Comment by ItsFl0ris** [comment]
same error here, try using an older version of python maybe 2.5 or 2.6

**Comment by arisros** [comment]
you have to choose with python 2 or 3

in core/tor.py
```
import socks
import socket

from os import system as shell
import sys
# replace with this at line 4
if sys.version_info.major == 2:
    from commands import getoutput
else:
    from subprocess import getoutput
# end paste
from time import sleep

.....
```

**Comment by nishitsingh13** [comment]
This is not working

**Comment by NoNameoN-A** [comment]
start with python3

**Comment by FireHead90544** [comment]
Thank you, sorry for late reply but haven't tried coz i don't need it now. still others who are facing these shall try above fixes. Hope it works. You may re-create this issue if still it shows the same.
