### ISSUE TITLE
Error: Unable to locate `https://www.youtube.com/watch?v=XQdotj8lJW8`

### ISSUE THREAD

**Issue by mushlih-almubarak** [Bitwise-01/YouTubeViews-#66]
I run this script:
`python youtube.py 100 https://www.youtube.com/watch?v=XQdotj8lJW8 2 5`
And this error appeared:
`Error: Unable to locate `https://www.youtube.com/watch?v=XQdotj8lJW8``
Even though when I opened the link, I still could
Why?

**Comment by kunaibox** [comment]
You're using it wrong, you need to specify a text file not a link. Create a text file in the directory called vids.txt or anything you like and put the link inside it. Then execute python youtube.py 100 vids.txt 2 5

**Comment by mushlih-almubarak** [comment]
Thank you

**Comment by Theodor1900** [comment]
Hi, i vave problem Error: Unable to locate `vids.txt` can some one help plese ?
